name: Deploy Website

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install web dependencies
        working-directory: web
        run: pnpm ci

      - name: Build Website
        working-directory: web
        run: pnpm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: web/dist

      - name: Install CDK dependencies
        working-directory: infra
        run: pnpm ci

      - name: Deploy to S3
        working-directory: infra
        run: pnpm run cdk deploy -- --require-approval never
