name: Production Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install PNPM Package Manager Globally
        run: npm install -g pnpm

      - name: Install Web Dependencies
        working-directory: ./web
        run: pnpm install

      - name: Build Application
        working-directory: ./web
        run: pnpm run build

      - name: Install Infra Dependencies
        working-directory: ./infra
        run: pnpm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3 with CDK
        working-directory: ./infra
        run: pnpm run cdk deploy -- --require-approval never
